spring.application.name=Ai-based

# Use environment variables for deployment
server.port=${PORT:9091}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ai_based}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:5668}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.main.allow-bean-definition-overriding=true

# Dialect auto-detected by Hibernate